#!/bin/bash
# script to build on linux
mkdir .vs
cd .vs

# clean up any old builds of xPlatAppx modules
find . -name *xPlatAppx* -d | xargs rm -r

cmake -DCMAKE_BUILD_TYPE=MinSizeRel -DLINUX=on ..
make
