//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MsixCoreInstaller.rc
//
#define IDS_STRING_FAILED_REQUEST       102
#define IDS_STRING_FAILED_COM_INITIALIZATION 103
#define IDI_ICONBIG                     103
#define IDS_STRING_HELP_OPTION_ADDPACKAGE 104
#define IDI_ICON2                       104
#define IDI_ICONSMALL                   104
#define IDS_STRING_HELP_OPTION_REMOVEPACKAGE 105
#define IDS_STRING_HELP_OPTION_QUIETMODE 106
#define IDS_STRING_HELP_OPTION_FINDALLPACKAGES 107
#define IDS_STRING_HELP_OPTION_FINDPACKAGE 108
#define IDS_STRING_HELP_OPTION_HELP     109
#define IDS_STRING_HELPTEXT             110
#define IDS_STRING_UI_CANCEL            111
#define IDS_STRING_UI_CLOSE             112
#define IDS_STRING_UI_TITLE             113
#define IDS_STRING_UI_INSTALL_COMPLETE  114
#define IDS_STRING_UI_UNINSTALL_COMPLETE 115
#define IDS_STRING_UI_COMPLETION_MESSAGE 116
#define IDS_STRING_INSTALLTEXT          117
#define IDS_STRING_UPDATETEXT           118
#define IDS_STRING_CANCEL_INSTALLPOPUP  119
#define IDS_STRING_CANCEL_POPUP_TITLE   120
#define IDS_STRING_CANCEL_UPDATEPOPUP   121
#define IDS_STRING_REINSTALLAPP         122
#define IDS_RUNFULLTRUST_CAPABILITY     123
#define IDS_STRING_ERROR_MSG            124

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
