jobs:
- job: iOS
  pool:
    vmImage: macOS-latest
  strategy:
    # TODO: add builds using xerces if needed.
    matrix:
      debug_x86:
        _arguments: -b Debug
        _artifact: iOS-x86chk
      release_x86:
        _arguments: -b MinSizeRel
        _artifact: iOS-x86
      release_x86_nobundle:
        _arguments: -b MinSizeRel -sb
        _artifact: iOS-x86-nobundle
      release_arm64:
        _arguments: -b MinSizeRel -arch arm64
        _artifact: iOS-arm64
      release_arm64_nobundle:
        _arguments: -b MinSizeRel -arch arm64 -sb
        _artifact: iOS-arm64-nobundle
  steps:
  - task: Bash@3
    displayName: Build
    inputs:
      targetType: filePath
      filePath: ./makeios.sh
      arguments: $(_arguments)
      failOnStderr: true
    condition: succeeded()

    # Note: We skip BVTs in Debug mode because of assert() and release_arm64
    # Only do BVTs for release_x86 because the emulator
    # The task will output to strerr Requested but did not find extension point with identifier Xcode.InterfaceBuilderBuildSupport.PlatformDefinition
    # This is something not related to us and it seems like the fix is updating the tools which we don't control.
    # https://github.com/fastlane/fastlane/discussions/20921
  - task: Bash@3
    displayName: iOS BVTs
    inputs:
      targetType: filePath
      filePath: './src/test/mobile/testios.sh'
      arguments: '-p iOSBVT/iOSBVT.xcodeproj -o TEST-MsixSDK-$(_artifact).xml'
      workingDirectory: './src/test/mobile/'
      failOnStderr: false
    condition: and(succeeded(), contains(variables['Agent.JobName'], 'release_x86'))

  - task: PublishTestResults@2
    displayName: 'Publish $(_artifact) Test Results'
    inputs:
      failTaskOnFailedTests: true
      testRunTitle: $(_artifact)
    condition: and(succeededOrFailed(), contains(variables['Agent.JobName'], 'release_x86'))

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: .vs
      Contents: |
        bin/makemsix
        bin/makemsix.dSYM/**
        lib/libmsix*
        lib/libmsix*/**
        src/msix/AppxPackaging.hpp
        src/msix/MSIXWindows.hpp
        src/msix/MsixErrors.hpp
        Package.nuspec
        build/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: succeededOrFailed()

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact $(_artifact)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: $(_artifact)
    condition: succeededOrFailed()
