XQilla Simple API Documentation
Result Class Reference
A scoped pointer wrapper for the lazily evaluated query result.
#include <Result.hpp>
Public Member Functions
Result (const Item::Ptr &item)
Result (const Sequence &seq)
Result (ResultImpl *impl)
Result (const Result &o)
Result & operator= (const Result &o)
~Result ()
ResultImpl * operator-> ()
Returns the underlying ResultImpl object.
const ResultImpl * operator-> () const
Returns the underlying ResultImpl object.
ResultImpl * get ()
Returns the underlying ResultImpl object.
const ResultImpl * get () const
Returns the underlying ResultImpl object.
bool isNull () const
Returns true if the underlying pointer is null.
EmptyResult * getEmpty () const
Detailed Description
A scoped pointer wrapper for the lazily evaluated query result.
Examples:
simple-basic.cpp, and simple-context-item.cpp.
Constructor & Destructor Documentation
Result::Result (const Item::Ptr & item)
Result::Result (const Sequence & seq)
Result::Result (ResultImpl * impl)
Result::Result (const Result & o)
Result::~Result ()
Member Function Documentation
const ResultImpl * Result::get () const [inline]
Returns the underlying ResultImpl object.
References getEmpty().
ResultImpl * Result::get () [inline]
Returns the underlying ResultImpl object.
References getEmpty().
EmptyResult* Result::getEmpty () const
Referenced by get().
bool Result::isNull () const [inline]
Returns true if the underlying pointer is null.
const ResultImpl * Result::operator-> () const [inline]
Returns the underlying ResultImpl object.
ResultImpl * Result::operator-> () [inline]
Returns the underlying ResultImpl object.
Result& Result::operator= (const Result & o)
The documentation for this class was generated from the following file:
Result.hpp