# Pipeline to create extension VSIX

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - tools/pipelines-tasks

pool:
  vmImage: 'windows-latest'

variables:
  tasksRoot: 'tools/pipelines-tasks'
  # Version number
  major: '1'
  minor: '0'
  # Set to 0 on next change to minor. This grew while using a classic pipeline.
  patch: $[counter(variables['minor'], 7)]

steps:
# Install the tools needed
- task: NodeTool@0
  displayName: 'Use Node 10.x'
  inputs:
    versionSpec: 10.x

- task: TfxInstaller@3
  displayName: 'Use Node CLI for Azure DevOps (tfx-cli): v0.7.x'

# Build the project
- task: PowerShell@2
  displayName: 'Build the project'
  inputs:
    targetType: filePath
    filePath: '$(tasksRoot)/build.ps1'
    arguments: BuildForProduction

# Run the tests
- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for test project'
  inputs:
    restoreSolution: '$(tasksRoot)/test/assets/HelloWorldUWPApp/HelloWorldApp.sln'

- powershell: |
    npx mocha
  displayName: 'Run the tests'
  workingDirectory: '$(tasksRoot)'
  env:
    SYSTEM_CULTURE: 'en-US'

# Set the version for each task as the Package step does not update the task.loc.json
# See https://github.com/microsoft/azure-devops-extension-tasks/issues/184
- powershell: |
   foreach ($path in $(Get-ChildItem -Depth 1 -Recurse -Include 'task.json','task.loc.json')) {
      $taskJson = Get-Content $path.FullName -Raw | ConvertFrom-Json
      $taskJson.version.Major = $(major)
      $taskJson.version.Minor = $(minor)
      $taskJson.version.Patch = $(patch)
      $taskJson | ConvertTo-Json -Depth 10 | Set-Content $path.FullName
   }
  workingDirectory: '$(tasksRoot)'
  displayName: 'Update tasks'' version'

# Package and sign the VSIX
- task: PackageAzureDevOpsExtension@3
  displayName: 'Package Extension: $(tasksRoot)'
  inputs:
    rootFolder: '$(tasksRoot)'
    patternManifest: 'vss-extension.json'
    outputPath: '$(Build.ArtifactStagingDirectory)\MsixPackagingExtension.vsix'
    publisherId: 'MSIX'
    extensionVersion: '$(major).$(minor).$(patch)'
    extensionVisibility: public
    updateTasksVersion: false

- task: ms.vss-governance-buildtask.governance-build-task-component-detection.ComponentGovernanceComponentDetection@0
  displayName: 'Component Detection'

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: 'ESRP CodeSigning'
  inputs:
    ConnectedServiceName: 'ESRP CodeSigning'
    FolderPath: '$(Build.ArtifactStagingDirectory)'
    Pattern: MsixPackagingExtension.vsix
    signConfigType: inlineSignParams
    inlineOperation: |
     [
      {
          "KeyCode" : "CP-233016",
          "OperationCode" : "OpcSign",
          "Parameters" : {
              "FileDigest" : "/fd SHA256"
          },
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
      },
      {
          "KeyCode" : "CP-233016",
          "OperationCode" : "OpcVerify",
          "Parameters" : {},
          "ToolName" : "sign",
          "ToolVersion" : "1.0"
      }
     ]

- task: PublishPipelineArtifact@1
  displayName: 'Publish VSIX artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)\MsixPackagingExtension.vsix'
    artifact: 'VSIX'
    publishLocation: 'pipeline'

# Publish privately
# Use different task IDs from public extension to prevent clashing.
# We need to update the IDs manually because the task doesn't do it.
# See https://github.com/microsoft/azure-devops-extension-tasks/issues/184
- powershell: |
    $newIds = (
      @{ Id = "10d89817-fdc8-572b-9e70-5a3300a49491"; Name = "AppInstallerFile" },
      @{ Id = "8d76d007-40aa-5704-abcd-fccba288ec3f"; Name = "MsixAppAttach" },
      @{ Id = "e1431997-aad9-5eeb-a649-a945fa6fd7d7"; Name = "MsixPackaging" },
      @{ Id = "bc2a3a10-c739-5277-acb1-32f8ffb6a382"; Name = "MsixSigning" }
    )
    foreach ($task in $newIds) {
      foreach ($jsonName in ('task.json', 'task.loc.json')) {
        $path = Join-Path $task.Name $jsonName
        $taskJson = Get-Content $path -Raw | ConvertFrom-Json
        $taskJson.id = $task.Id
        $taskJson | ConvertTo-Json -Depth 10 | Set-Content $path
      }
    }
  workingDirectory: $(tasksRoot)
  displayName: 'Update tasks'' IDs for private'

- task: PublishAzureDevOpsExtension@3
  displayName: 'Publish Extension'
  inputs:
    connectedServiceName: 'Visual Studio Marketplace - MSIX'
    fileType: 'manifest'
    rootFolder: '$(tasksRoot)'
    patternManifest: 'vss-extension.json'
    publisherId: 'MSIX'
    extensionId: 'msix-ci-automation-task-dev'
    extensionName: 'MSIX Packaging (Preview)'
    extensionVersion: '$(major).$(minor).$(patch)'
    updateTasksVersion: false
    # updateTasksId: true
    extensionVisibility: 'privatepreview'
