//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by msixmgr.rc
//
#define IDS_STRING_FAILED_REQUEST       102
#define IDS_STRING_FAILED_COM_INITIALIZATION 103
#define IDI_ICONBIG                     103
#define IDS_STRING_HELP_OPTION_ADDPACKAGE 104
#define IDI_ICON2                       104
#define IDI_ICONSMALL                   104
#define IDS_STRING_HELP_OPTION_REMOVEPACKAGE 105
#define IDS_STRING_HELP_OPTION_QUIETMODE 106
#define IDS_STRING_HELP_OPTION_FINDALLPACKAGES 107
#define IDS_STRING_HELP_OPTION_FINDPACKAGE 108
#define IDS_STRING_HELP_OPTION_HELP     109
#define IDS_STRING_HELPTEXT_USAGE       110
#define IDS_STRING_UI_CANCEL            111
#define IDS_STRING_UI_CLOSE             112
#define IDS_STRING_UI_TITLE             113
#define IDS_STRING_UI_INSTALL_COMPLETE  114
#define IDS_STRING_UI_UNINSTALL_COMPLETE 115
#define IDS_STRING_UI_COMPLETION_MESSAGE 116
#define IDS_STRING_INSTALLTEXT          117
#define IDS_STRING_UPDATETEXT           118
#define IDS_STRING_CANCEL_INSTALLPOPUP  119
#define IDS_STRING_CANCEL_POPUP_TITLE   120
#define IDS_STRING_CANCEL_UPDATEPOPUP   121
#define IDS_STRING_REINSTALLAPP         122
#define IDS_RUNFULLTRUST_CAPABILITY     123
#define IDS_STRING_HELPTEXT_DESCRIPTION 125
#define IDS_STRING_HELPTEXT_OPTIONS     126
#define IDS_STRING_HELP_OPTION_UNPACK   127
#define IDS_STRING_HELP_OPTION_UNPACK_PACKAGEPATH 128
#define IDS_STRING_HELP_OPTION_UNPACK_DESTINATION 129
#define IDS_STRING_HELP_OPTION_UNPACK_APPLYACLS 130
#define IDS_STRING_HELP_OPTION_UNPACK_VALIDATESIGNATURE 131
#define IDS_STRING_HELP_OPTION_APPLYACLS 132
#define IDS_STRING_HELP_OPTION_APPLYACLS_PACKAGEPATH 133
#define IDS_STRING_LOADING_PACKAGE_ERROR 134
#define IDS_STRING_WXS_ERROR_PART1      135
#define IDS_STRING_WXS_ERROR_PART2      136
#define IDS_STRING_LAUNCH_CHECKBOX      137
#define IDS_STRING_LAUNCHBUTTON         138
#define IDS_STRING_PUBLISHER            139
#define IDS_STRING_VERSION              140
#define IDS_STRING_CAPABILITIES         141
#define IDS_STRING_INSTALLING_APP       142
#define IDS_STRING_ERROR_REASON_TEXT    143
#define IDS_STRING_LOADING_PACKAGE      144
#define IDS_STRING_LOADING_PACKAGE_OPEN_ERROR 145
#define IDS_STRING_SIG_MISSING_ERROR 146
#define IDS_STRING_ROOT_SIG_UNTRUSTED_ERROR 147
#define IDS_STRING_CANNOT_OPEN_PACKAGE_ERROR 148
#define IDS_STRING_GENERIC_INSTALL_FAILED_ERROR 149
#define IDS_STRING_INVALID_TDF_ERROR 150
#define IDS_STRING_INVALID_ARCHITECTURE_ERROR 151
#define IDS_STRING_PACKAGE_DOWNGRADE_ERROR 152
#define IDS_STRING_USER_CANCELLED_INSTALL_ERROR 153
#define IDS_STRING_HELP_OPTION_UNPACK_CREATE 154
#define IDS_STRING_HELP_OPTION_UNPACK_ROOTDIRECTORY 155
#define IDS_STRING_HELP_OPTION_UNPACK_FILETYPE 156
#define IDS_STRING_HELP_OPTION_MOUNTIMAGE 157
#define IDS_STRING_HELP_OPTION_MOUNTIMAGE_IMAGEPATH 158
#define IDS_STRING_HELP_OPTION_UNMOUNTIMAGE 159
#define IDS_STRING_HELP_OPTION_UNMOUNTIMAGE_VOLUMEID 160
#define IDS_STRING_HELP_OPTION_MOUNT_FILETYPE 161
#define IDS_STRING_HELP_OPTION_UNPACK_VHDSIZE 162
#define IDS_STRING_HELP_OPTION_MOUNT_READONLY 163
#define IDS_STRING_HELP_OPTION_OUTPUT 164
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        122
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
